### ISSUE TITLE
group_by_day_of_week - always returning 0 for Sunday

### ISSUE THREAD

**Issue by treiff** [ankane/groupdate#72] opened 2015-01-16 00:13 UTC
I'll preface this by saying I am a beginner, but do think there may be a bug here.  However, it could also me making a stupid mistake.  

I have an array of tweets i've gathered using the twitter API.  There is no database, I am just pulling data from twitter.  So I have this code:
```
days_hash = tweets.group_by_day_of_week { |t| t.created_at }
days_hash.merge(days_hash) { | k, v | v.count }
```
So, from this I get a hash with days 0-6 as keys and x as values of tweets corresponding to that particular day.  The issue is Sunday is always 0 even know if I go back to the tweets array and run:
```
count = 0
tweets.each do |t|
  if t.created_at.wday == 0
    count += 1
  end
end

count
=> 16
```
Also, the length of the original array (139) vs the total count of the days_hash (128), doesn't really make sense to me 11 when the count of Sunday tweets is 16?  

I did also mess around with Groupdate.time_zone, setting it to match the tweets created_at, obviously it made a subtle difference in counts depending on the tweet but Sunday was still 0.   

Ruby v is 2.1.5, let me know if there is any other info I can provide to help out, or if it's just me missing something.  Thanks!

**Comment by ankane** [comment] 2016-07-24 10:43
Hey @treiff, earlier today, a bug was fixed with enumerable and `group_by_day_of_week`, which is likely the cause of this.

**Closed by ankane** 2016-07-24 10:43 UTC
